# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eba85e2292c5449ae9bbe826abe51ad73078824a12df7979181e7ea2e91ec7994d677b776563282669efb618d7d7b0fb4c14e3cbe303760627a8f6a748fff25

test:
  secret_key_base: 80f663a2c9a0906c588283e28b7fee1e55bdc4f4aa791da68527780cf0b27d00182efd9f92f0bb5e847993e42c12c98a18b9af971ed2a05f9e2e068210cfa108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
